language: node_js
node_js:
  - "8"
services:
  - mysql
env:
  - DB_USER=root
  - DB_NAME=koa
  - PORT=3000
  - NODE_ENV=test

before_install:
  - mysql -e 'CREATE DATABASE koa;'

install:
  - npm install

script:
  - npm run db
