version: '2'

services:

  app:
    image: zcong/dc-server-koa:latest
    links:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql/koa
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    expose:
      - 3000

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=koa
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
