version: 2
jobs:
  build:
    working_directory: ~/dc-server/dc-server-koa
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:8.0.0
      # CircleCI Mysql
      - image: circleci/mysql:latest
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: dc-server-koa
    steps:
      - checkout
      - run:
          name: Waiting for Mysql to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Mysql && exit 1
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependences
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: mock and test
          environment:
            DATABASE_URL: "mysql://root:@:3306/dc-server-koa"
            PORT: 3000
            NODE_ENV: test
          command: |
            yarn db
            yarn test
